# Generated by Django 4.2.4 on 2023-09-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_alter_curso_options_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jpgcursos'),
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
