# Generated by Django 4.2.4 on 2023-09-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_curso_detalles_curso_duracion_curso_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jpgestudiante/'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='jpgcursos/'),
        ),
    ]
